# pull official base image
FROM node:14.19.3-alpine

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# certificates
COPY docker/myCA.pem /root/my-root-ca.crt
RUN cat /root/my-root-ca.crt >> /etc/ssl/certs/ca-certificates.crt

RUN apk --no-cache add ca-certificates \
    && rm -rf /var/cache/apk/*
COPY docker/myCA.pem /usr/local/share/ca-certificates/ca-certificates.crt
RUN update-ca-certificates

RUN apk --no-cache add curl

# install app dependencies
COPY package.json ./
COPY package-lock.json ./
RUN npm install --silent
RUN npm install react-scripts@5.0.1 -g --silent

# add app
COPY . ./

# start app
CMD ["npm", "start"]