version: '3.7'

services:
  eshop.api:
    image: eshopapi
    build:
      context: ../server
      dockerfile: Api/dockerfile
    environment:
      - ASPNETCORE_URLS=http://*:5012
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - eshop.seq
    ports:
      - "5012:5012"
    networks:
      - eshopnet

  eshop.ui:
    image: eshopui
    build:
      context: ../client
      dockerfile: dockerfile
    depends_on:
      - eshop.seq
    ports:
      - "3000:3000"
    networks:
      - eshopnet

  eshop.seq:
    image: datalust/seq
    #restart: unless-stopped
    ports:
      - "5342:80"
    environment:
      - ACCEPT_EULA=Y
    networks:
      - eshopnet

  eshop.db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Australia01!
    ports:
      - "1434:1433"
    volumes:
      - sqlvolume:/var/opt/mssql
    networks:
      - eshopnet

networks:
  eshopnet: {}
  
volumes:
  sqlvolume:
    external: true